#!/bin/bash

echo "🚀 БЫСТРЫЙ ДЕПЛОЙ ФРОНТЕНДА НА СЕРВЕР"
echo "======================================"

# Замените на ваш реальный IP сервера
SERVER_IP="YOUR_SERVER_IP"
SERVER_USER="root"
SERVER_PATH="/opt/advakod

echo "📋 Инструкции для деплоя:"
echo ""
echo "1. Отредактируйте IP сервера в этом скрипте:"
echo "   nano БЫСТРЫЙ_ДЕПЛОЙ.sh"
echo "   Замените YOUR_SERVER_IP на ваш реальный IP"
echo ""
echo "2. Запустите деплой:"
echo "   ./БЫСТРЫЙ_ДЕПЛОЙ.sh"
echo ""
echo "3. Или выполните команды вручную:"
echo ""
echo "   # Копируем build на сервер"
echo "   rsync -avz --delete frontend/build/ ${SERVER_USER}@${SERVER_IP}:${SERVER_PATH}/frontend/build/"
echo ""
echo "   # Подключаемся к серверу и перезапускаем"
echo "   ssh ${SERVER_USER}@${SERVER_IP}"
echo "   cd ${SERVER_PATH}"
echo "   docker-compose -f docker-compose.prod.yml restart frontend"
echo ""
echo "4. Проверяем результат:"
echo "   Откройте https://advacodex.com"
echo "   Сайт должен загрузиться с полным интерфейсом!"
echo ""
echo "✅ Готовый build находится в: frontend/build/"
echo "✅ Содержит правильные URL: advacodex.com"
