groups:
  - name: ai_lawyer_alerts
    rules:
      # High-level service alerts
      - alert: AILawyerServiceDown
        expr: up{job="ai-lawyer"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "AI-Lawyer service is down"
          description: "AI-Lawyer service has been down for more than 1 minute"
          
      - alert: HighErrorRate
        expr: rate(ai_lawyer_http_requests_total{status_code=~"5.."}[5m]) / rate(ai_lawyer_http_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes"
          
      - alert: HighResponseTime
        expr: ai_lawyer_http_request_duration_seconds{quantile="0.95"} > 5
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High response time"
          description: "95th percentile response time is {{ $value }}s"
          
      # AI/ML specific alerts
      - alert: AIInferenceLatencyHigh
        expr: ai_lawyer_ai_inference_duration_seconds{quantile="0.95"} > 30
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "AI inference latency is high"
          description: "95th percentile AI inference time is {{ $value }}s for model {{ $labels.model_type }}"
          
      - alert: AIInferenceErrorRate
        expr: rate(ai_lawyer_ai_inference_requests_total{status="error"}[5m]) / rate(ai_lawyer_ai_inference_requests_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High AI inference error rate"
          description: "AI inference error rate is {{ $value | humanizePercentage }} for model {{ $labels.model_type }}"
          
      - alert: TokenGenerationSlow
        expr: ai_lawyer_ai_tokens_generated_per_second < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Token generation is slow"
          description: "Token generation rate is {{ $value }} tokens/sec, which is below threshold"
          
      # Rate limiting alerts
      - alert: HighRateLimitingActivity
        expr: rate(ai_lawyer_rate_limit_blocked_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High rate limiting activity"
          description: "Rate limiting is blocking {{ $value }} requests/sec"
          
      - alert: RateLimitTokensExhausted
        expr: ai_lawyer_rate_limit_tokens_remaining < 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Rate limit tokens nearly exhausted"
          description: "Only {{ $value }} rate limit tokens remaining for endpoint {{ $labels.endpoint_type }}"
          
      # Cache performance alerts
      - alert: LowCacheHitRate
        expr: rate(ai_lawyer_cache_hits_total[5m]) / (rate(ai_lawyer_cache_hits_total[5m]) + rate(ai_lawyer_cache_misses_total[5m])) < 0.7
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }} for cache {{ $labels.cache_type }}"
          
      - alert: CacheEvictionsHigh
        expr: rate(ai_lawyer_cache_evictions_total[5m]) > 100
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High cache eviction rate"
          description: "Cache eviction rate is {{ $value }} evictions/sec for cache {{ $labels.cache_type }}"
          
      # Database alerts
      - alert: DatabaseConnectionsHigh
        expr: ai_lawyer_database_connections_active > 50
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High database connection count"
          description: "Active database connections: {{ $value }}"
          
      - alert: DatabaseQuerySlow
        expr: ai_lawyer_database_query_duration_seconds{quantile="0.95"} > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries"
          description: "95th percentile database query time is {{ $value }}s"
          
      # Vector store alerts
      - alert: VectorStoreLatencyHigh
        expr: ai_lawyer_vector_store_duration_seconds{quantile="0.95"} > 2
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High vector store latency"
          description: "95th percentile vector store operation time is {{ $value }}s for operation {{ $labels.operation }}"
          
      - alert: VectorStoreErrorRate
        expr: rate(ai_lawyer_vector_store_operations_total{status="error"}[5m]) / rate(ai_lawyer_vector_store_operations_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High vector store error rate"
          description: "Vector store error rate is {{ $value | humanizePercentage }}"
          
      # System resource alerts
      - alert: HighCPUUsage
        expr: ai_lawyer_system_cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"
          
      - alert: HighMemoryUsage
        expr: ai_lawyer_system_memory_usage_percent > 85
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}%"
          
      - alert: LowDiskSpace
        expr: ai_lawyer_system_disk_usage_percent > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Disk usage is {{ $value }}% on {{ $labels.path }}"
          
      # Business logic alerts
      - alert: LowChatSessionActivity
        expr: rate(ai_lawyer_chat_sessions_total[1h]) < 0.1
        for: 30m
        labels:
          severity: info
        annotations:
          summary: "Low chat session activity"
          description: "Chat session rate is {{ $value }} sessions/hour, which is unusually low"
          
      - alert: HighLegalQueryFailureRate
        expr: rate(ai_lawyer_legal_queries_total{status="error"}[5m]) / rate(ai_lawyer_legal_queries_total[5m]) > 0.1
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High legal query failure rate"
          description: "Legal query failure rate is {{ $value | humanizePercentage }}"
          
      - alert: DocumentAnalysisBacklog
        expr: ai_lawyer_document_analysis_queue_size > 100
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Document analysis backlog"
          description: "Document analysis queue has {{ $value }} pending items"